/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseView: typeof import('./src/components/BaseView.vue')['default']
    GreetComponent: typeof import('./src/components/GreetComponent.vue')['default']
    MeTruyenChuDownloadView: typeof import('./src/components/MeTruyenChuDownloadView.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    VerticalBar: typeof import('./src/components/VerticalBar.vue')['default']
  }
}
